spring:
  application:
    name: book-service
  # MongoDB
  data:
    mongodb:
      host: localhost
      port: 27017
      database: book-service
      
  # GraphQL API URL
  graphql:
    path: /api/graphql

server:
  port: 8081

# S3 Configuration
app:
  book:
    image:
      bucket: bookstore-book-images-dev
      base-url: https://bookstore-book-images-dev.s3.us-east-1.amazonaws.com
      folder: books

eureka:
  client:
    serviceUrl:
      defaultZone: http://eureka:password@localhost:8761/eureka

# Zipkin
management:
  zipkin:
    tracing:
      endpoint: http://localhost:9411/api/v2/spans
  tracing:
    sampling:
      probability: 1.0

  # Actuator Prometheus Endpoint
  endpoints:
    web:
      exposure:
        include: prometheus

logging:
  pattern:
    level: "%5p [${spring.application.name:},%X{traceId:-},%X{spanId:-}]"