spring:
  data:
    mongodb:
      host: mongo
      port: 27017
      database: book-service

management:
  zipkin:
    tracing:
      endpoint: http://zipkin:9411/api/v2/spans

eureka:
  client:
    serviceUrl:
      defaultZone: http://discovery-server:8761/eureka
  instance:
    preferIpAddress: true

app:
  book:
    image:
      bucket: bookstore-book-images-dev
      base-url: https://bookstore-book-images-dev.s3.us-east-1.amazonaws.com
      folder: books    